<a href="https://colab.research.google.com/github/SHAZAN01/Data_Analysis/blob/main/13_Numpy_100_exercise_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy exercise top 100 problems**

In [ ]:
# 1. Import the numpy package under the name np
import numpy as np

In [ ]:
# 2. Print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [ ]:
# 3. Create a null vector of size 10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 4. How to find the memory size of any array
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [ ]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [ ]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 8. Reverse a vector (first element becomes last) (★☆☆)
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [ ]:
# 11. Create a 3x3 identity matrix (★☆☆)
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 12. Create a 3x3x3 array with random values (★☆☆)
Z = np.random.random((3,3,3))
print(Z)

[[[0.88596332 0.57334356 0.90518532]
  [0.50282516 0.22204796 0.99666145]
  [0.31753265 0.67871078 0.74641835]]

 [[0.78228224 0.30815878 0.36152246]
  [0.74619508 0.72420905 0.67781207]
  [0.64045874 0.1671289  0.31655642]]

 [[0.20033102 0.88852566 0.81002203]
  [0.10461689 0.52539303 0.91890431]
  [0.55887453 0.56595471 0.45163884]]]


In [ ]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.008039152455521004 0.9882165662204092


In [ ]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)
Z = np.random.random(30)
m = Z.mean()
print(m)

0.35481772648493703


In [ ]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 17. What is the result of the following expression? (★☆☆)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [ ]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [ ]:
# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 22. Normalize a 5x5 random matrix (★☆☆)
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.8720347  -0.3274759   1.50468504  0.51778311 -0.85120414]
 [-1.01286769  1.40572229 -0.68389573  1.49931582 -0.65323631]
 [-1.06820499 -0.06346668 -1.17504261 -0.40747119  1.33159019]
 [-0.85790978  0.95900506 -0.8388317  -0.08066555  1.51531613]
 [-1.23612239  1.47144186  1.03594297 -0.88727705 -0.22509606]]


In [ ]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-23-196913c491d4>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [ ]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
### Author: Evgeni Burovski####

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
# 26. What is the output of the following script? (★☆☆)
#### Author: Jake VanderPlas#####

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
# # 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
# # Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z

In [ ]:
# 28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-31-4e159d6ee109>:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-31-4e159d6ee109>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [ ]:
# 29. How to round away from zero a float array ? (★☆☆)
##### Author: Charles R Harris######

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-9. -7. -6. -8.  2.  2. -7. -2.  3. -8.]


In [ ]:
# 30. How to find common values between two arrays? (★☆☆)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 3 6 7 9]


In [ ]:
# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)[not understand]
# Suicide mode on
# defaults = np.seterr(all="ignore")
# Z = np.ones(1) / 0

# # Back to sanity
# _ = np.seterr(**defaults)

# An equivalent way, with a context manager:

# with np.errstate(divide='ignore'):
#     Z = np.ones(1) / 0

In [ ]:
# 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-49-52f0ace13fa8>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [ ]:
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')


In [ ]:
# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
# 36. Extract the integer part of a random array using 5 different methods (★★☆)
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[0. 0. 0. 4. 4. 5. 7. 6. 8. 2.]
[0. 0. 0. 4. 4. 5. 7. 6. 8. 2.]
[0. 0. 0. 4. 4. 5. 7. 6. 8. 2.]
[0 0 0 4 4 5 7 6 8 2]
[0. 0. 0. 4. 4. 5. 7. 6. 8. 2.]


In [ ]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
# 40. Create a random vector of size 10 and sort it (★★☆)
Z = np.random.random(10)
Z.sort()
print(Z)

[0.07442639 0.36263291 0.412612   0.42386778 0.62349607 0.66249358
 0.73074897 0.78524207 0.8178192  0.86505957]


In [ ]:
# 41. How to sum a small array faster than np.sum? (★★☆)
##### Author: Evgeni Burovski####

Z = np.arange(10)
np.add.reduce(Z)

45

In [ ]:
# 42. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [ ]:
# 43. Make an array immutable (read-only) (★★☆)
# Z = np.zeros(10)
# Z.flags.writeable = False
# Z[0] = 1

In [ ]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.99126585 0.79537259 0.5197261  0.91231054 1.07631751 0.88688984
 1.04063477 1.08008195 0.94110793 1.08906852]
[0.15501181 1.41915204 1.00975298 0.77060248 0.53595652 0.79415131
 0.32446166 0.45438165 0.12011371 0.84688468]


In [ ]:
# 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.00159222 0.20454517 0.57477097 0.74445652 0.58297825 0.44788661
 0.42741933 0.05610169 0.         0.86467571]


In [ ]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
##### Author: Evgeni Burovski#####

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [ ]:
# 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
# 49. How to print all the values of an array? (★★☆)[doubt??????????]
# np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

16


In [ ]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-70-dc9a822256a9>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [ ]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.37641196 0.46396194 0.73771266 0.87870081 0.66114067
  0.45556465 0.21971657 0.69814157 0.14342622]
 [0.37641196 0.         0.32778985 0.48749061 0.59007521 0.48257043
  0.82783396 0.59125485 0.33038727 0.29799004]
 [0.46396194 0.32778985 0.         0.804746   0.88615433 0.81023842
  0.8818463  0.60553081 0.55780802 0.32076919]
 [0.73771266 0.48749061 0.804746   0.         0.1571812  0.14166131
  1.09742485 0.94613703 0.34678716 0.73494823]
 [0.87870081 0.59007521 0.88615433 0.1571812  0.         0.29249003
  1.252103   1.09155678 0.35878017 0.86131202]
 [0.66114067 0.48257043 0.81023842 0.14166131 0.29249003 0.
  0.98418374 0.85732499 0.43907762 0.68406358]
 [0.45556465 0.82783396 0.8818463  1.09742485 1.252103   0.98418374
  0.         0.27741534 1.13712912 0.57820067]
 [0.21971657 0.59125485 0.60553081 0.94613703 1.09155678 0.85732499
  0.27741534 0.         0.91668356 0.31323126]
 [0.69814157 0.33038727 0.55780802 0.34678716 0.35878017 0.43907762
  1.13712912 0.91668

In [ ]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 54. How to read the following file? (★★☆)
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-73-0af6546de3a6>:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


In [ ]:
# 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
# 56. Generate a generic 2D Gaussian-like array (★★☆)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [ ]:
# 57. How to randomly place p elements in a 2D array? (★★☆)
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 58. Subtract the mean of each row of a matrix (★★☆)
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.16798689  0.36058454  0.11034301  0.26604236 -0.09307916 -0.08723618
  -0.33154265  0.2432798  -0.44621919 -0.19015942]
 [-0.05535157 -0.48985493  0.17658895  0.36507916  0.26702573 -0.28633817
   0.1241594   0.21651851 -0.41720521  0.09937811]
 [ 0.16434788  0.19610215 -0.00878496  0.13256636  0.00741354  0.37459374
   0.01899797 -0.36243304 -0.36299912 -0.15980451]
 [-0.33249878  0.33022987 -0.49750474  0.16306822  0.09878218  0.26842899
   0.1153934   0.19275534 -0.58380696  0.24515247]
 [-0.28517226 -0.3271002   0.04852732  0.33116714 -0.21745679  0.15005502
  -0.04702926  0.21453801  0.28855124 -0.15608022]]


In [ ]:
# 59. How to sort an array by the nth column? (★★☆)
######## Author: Steve Tjoa########

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 8 3]
 [6 1 0]
 [0 1 2]]
[[6 1 0]
 [0 1 2]
 [8 8 3]]


In [ ]:
# 60. How to tell if a given 2D array has null columns? (★★☆)
######## Author: Warren Weckesser#####

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


In [ ]:
# 61. Find the nearest value from a given value in an array (★★☆)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5016509805754985


In [ ]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
# 63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [ ]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
########## Author: Brett Olsen#########

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[1. 2. 2. 7. 2. 4. 2. 4. 4. 2.]
[ 1.  3.  3. 13.  3.  7.  3.  7.  7.  3.]


In [ ]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
########### Author: Alan G Isaac###########

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
######### Author: Nadav Horesh##########

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first.
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [ ]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[71 37 54 63]
 [43 66 54 45]
 [57 57 67 47]]
[[71 37 54 63]
 [43 66 54 45]
 [57 57 67 47]]


In [ ]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
########### Author: Jaime Fernández del Río#######

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.50326023 0.43154472 0.51639062 0.4457534  0.71331821 0.6160355
 0.3567616  0.62488307 0.48283218 0.59941019]
0    0.503260
1    0.431545
2    0.516391
3    0.445753
4    0.713318
5    0.616036
6    0.356762
7    0.624883
8    0.482832
9    0.599410
dtype: float64


In [ ]:
# 69. How to get the diagonal of a dot product? (★★★)
########### Author: Mathieu Blondel#########

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.59929712, 0.73813303, 0.49901796, 1.11330244, 0.92173596])

In [ ]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
########### Author: Warren Weckesser#########

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [ ]:
# 72. How to swap two rows of an array? (★★★)
########### Author: Eelco Hoogendoorn###########

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)
############# Author: Nicolas P. Rougier#############

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 39) ( 4, 65) (22, 24) (22, 39) (23, 32) (23, 47) (24, 39) (25, 52)
 (25, 85) (32, 47) (36, 43) (36, 58) (39, 65) (40, 78) (40, 83) (43, 58)
 (46, 68) (46, 94) (47, 57) (47, 58) (50, 52) (50, 88) (52, 85) (52, 88)
 (57, 58) (59, 67) (59, 83) (67, 83) (68, 94) (78, 83)]


In [ ]:
# 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
############ Author: Jaime Fernández del Río##############

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [ ]:
# 75. How to compute averages using a sliding window over an array? (★★★)
############ Author: Jaime Fernández del Río#########

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [ ]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
############# Author: Joe Kington / Erik Rigtorp#############
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
########## Author: Nathaniel J. Smith############

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.80363273,  0.05821874, -0.86419953,  0.04387577, -0.09270808,
       -0.90177768,  0.77873267, -0.27167856, -0.80108934,  0.3724225 ,
       -0.37226921, -0.39223987, -0.95288197,  0.78674498, -0.41022315,
       -0.91593463,  0.73334166, -0.11318327, -0.324554  , -0.20498589,
        0.43753166, -0.05303384,  0.4578309 ,  0.62774944,  0.2629218 ,
        0.38941443,  0.19049222, -0.19347286,  0.37831572, -0.92586906,
        0.74789832, -0.37196887, -0.48528359,  0.82086944,  0.27848923,
        0.59858296, -0.31607589,  0.46389865,  0.10244956, -0.09246261,
       -0.89248937, -0.24190024,  0.11160152, -0.99016923, -0.95458327,
       -0.65851574,  0.6805621 , -0.10599406,  0.30661022, -0.70101919,
        0.42409423, -0.23707917,  0.51082146, -0.60305011,  0.38806009,
        0.29969212,  0.86588023, -0.46505756, -0.16525476, -0.4081627 ,
       -0.27619492, -0.15121711,  0.10200659,  0.44550522, -0.04289244,
        0.9877303 ,  0.95782333,  0.11667971,  0.98216532, -0.71

In [ ]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.22346659  5.0804199   6.00326734  1.48548689  4.12547875  0.71971672
  4.46558085  7.96687012 10.90518408 10.09449384]


In [ ]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
############## Author: Italmassov Kuanysh##################

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[15.09962215  8.07288551  6.16180475 11.42607594  2.12632468 17.09522361
   7.19814058 12.49223536  6.40330852 15.06203086]
 [ 9.36455569  5.85221499  1.06753522  5.82195955  2.2183648  11.63302691
   4.62723937  6.71630958  0.66226963 11.2254389 ]
 [ 2.94843637  9.45004005  8.63697912  0.42436553  9.26963791  6.9897526
   7.59085849  0.66745895  5.82337562 11.56428879]
 [ 0.97484672  9.78519256 11.11399999  1.34654427 10.55720108  5.37532485
   7.76167681  2.82174749  7.81037949 11.08106587]
 [ 7.81319848  5.04281861  0.17305193  4.27610336  2.00484731 10.10512575
   3.73142111  5.1855339   0.88854679 10.02872276]
 [ 3.19180453  0.79327132  8.91135147  6.70341125  0.38235473  0.7562631
   2.71396544  5.65915872 11.88873818  1.467591  ]
 [10.65310899  1.51355923  5.39779495  6.38751001  3.32877699 11.69301172
   0.5600584   8.7473235   2.00214915  8.40405446]
 [ 0.68895182  7.36969484 11.42547729  3.22630388  8.56041834  3.36330243
   5.31516098  4.22891305  9.4576092   8.61938014]
 [

In [ ]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
############# Author: Nicolas Rougier################

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 2 2 5 4 2 4 6 8 2]
 [9 8 4 5 5 8 6 1 6 9]
 [8 5 5 7 1 2 8 5 2 4]
 [7 3 2 7 5 2 1 3 7 3]
 [5 4 7 6 3 8 0 0 1 8]
 [0 3 4 4 8 8 2 0 9 5]
 [6 9 6 7 3 7 5 1 7 2]
 [5 3 9 8 5 4 6 2 5 8]
 [0 5 5 6 2 7 9 6 2 8]
 [6 0 9 8 1 5 7 7 0 7]]
[[0 0 0 0 0]
 [0 7 2 2 5]
 [0 9 8 4 5]
 [0 8 5 5 7]
 [0 7 3 2 7]]


<ipython-input-99-1139094783f6>:26: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [ ]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
#################### Author: Stefan van der Walt#################

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
# 82. Compute a matrix rank (★★★)
############## Author: Stefan van der Walt###########

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [ ]:
# 83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


In [ ]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
############## Author: Chris Barker################

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 0 1]
   [3 1 3]
   [0 3 4]]

  [[0 1 1]
   [1 3 4]
   [3 4 0]]

  [[1 1 3]
   [3 4 2]
   [4 0 1]]

  [[1 3 2]
   [4 2 4]
   [0 1 1]]

  [[3 2 0]
   [2 4 4]
   [1 1 3]]

  [[2 0 1]
   [4 4 2]
   [1 3 4]]

  [[0 1 4]
   [4 2 1]
   [3 4 4]]

  [[1 4 4]
   [2 1 4]
   [4 4 1]]]


 [[[3 1 3]
   [0 3 4]
   [4 4 0]]

  [[1 3 4]
   [3 4 0]
   [4 0 4]]

  [[3 4 2]
   [4 0 1]
   [0 4 1]]

  [[4 2 4]
   [0 1 1]
   [4 1 1]]

  [[2 4 4]
   [1 1 3]
   [1 1 1]]

  [[4 4 2]
   [1 3 4]
   [1 1 1]]

  [[4 2 1]
   [3 4 4]
   [1 1 1]]

  [[2 1 4]
   [4 4 1]
   [1 1 0]]]


 [[[0 3 4]
   [4 4 0]
   [1 2 1]]

  [[3 4 0]
   [4 0 4]
   [2 1 1]]

  [[4 0 1]
   [0 4 1]
   [1 1 1]]

  [[0 1 1]
   [4 1 1]
   [1 1 1]]

  [[1 1 3]
   [1 1 1]
   [1 1 3]]

  [[1 3 4]
   [1 1 1]
   [1 3 1]]

  [[3 4 4]
   [1 1 1]
   [3 1 2]]

  [[4 4 1]
   [1 1 0]
   [1 2 2]]]


 [[[4 4 0]
   [1 2 1]
   [3 4 0]]

  [[4 0 4]
   [2 1 1]
   [4 0 2]]

  [[0 4 1]
   [1 1 1]
   [0 2 0]]

  [[4 1 1]
   [1 1 1]
   [2 0 3]]

  [[1 1 1]
   

In [ ]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
################## Author: Eric O. Lebigot#################
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1  8  9  4 11]
 [ 8  2  7  4 15]
 [ 9  7  3 42 11]
 [ 4  4 42  4  9]
 [11 15 11  9  5]]


In [ ]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [ ]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
############# Author: Robert Kern##############

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [ ]:
# 88. How to implement the Game of Life using numpy arrays? (★★★)
################ Author: Nicolas Rougier##########################

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 1 ... 1 1 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# 89. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9998 9999 9997 9995]


In [ ]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
############## Author: Stefan Van der Walt###################

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
# 91. How to create a record array from a regular array? (★★★)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [ ]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
# Author: Ryan G.

x = np.random.rand(57)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.36 µs ± 42.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.37 µs ± 502 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.23 µs ± 80.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[]


In [ ]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 1 0]
 [2 3 0]
 [1 0 2]
 [2 2 3]
 [1 0 0]
 [4 1 4]
 [0 1 3]
 [3 2 3]
 [0 2 1]
 [0 3 3]]
[[1 1 0]
 [2 3 0]
 [1 0 2]
 [2 2 3]
 [1 0 0]
 [4 1 4]
 [0 1 3]
 [3 2 3]
 [0 2 1]
 [0 3 3]]
[[1 1 0]
 [2 3 0]
 [1 0 2]
 [2 2 3]
 [1 0 0]
 [4 1 4]
 [0 1 3]
 [3 2 3]
 [0 2 1]
 [0 3 3]]


In [ ]:
# 95. Convert a vector of ints into a matrix binary representation (★★★)
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [ ]:
# 96. Given a two dimensional array, how to extract unique rows? (★★★)
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [1 0 0]
 [1 1 1]]
[[0 0 1]
 [1 0 0]
 [1 1 1]]


In [ ]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.01401394, 0.09810113, 0.10136273, 0.20380575, 0.11550287,
        0.10624863, 0.34019654, 0.14040671, 0.10986794, 0.08820531],
       [0.00495189, 0.03466445, 0.03581695, 0.07201563, 0.04081343,
        0.03754341, 0.1202099 , 0.04961331, 0.03882231, 0.03116772],
       [0.01949994, 0.13650452, 0.14104292, 0.28358904, 0.16071847,
        0.1478415 , 0.47337236, 0.19537135, 0.15287765, 0.12273481],
       [0.02288648, 0.16021113, 0.16553772, 0.33283969, 0.1886303 ,
        0.17351701, 0.55558252, 0.22930132, 0.17942778, 0.14405005],
       [0.0291672 , 0.20417778, 0.21096614, 0.42418069, 0.240396  ,
        0.22113517, 0.7080507 , 0.29222834, 0.22866804, 0.18358162],
       [0.01705596, 0.11939604, 0.12336564, 0.24804607, 0.1405752 ,
        0.12931214, 0.41404336, 0.17088494, 0.13371709, 0.10735213],
       [0.0197407 , 0.13818988, 0.14278433, 0.2870904 , 0.1627028 ,
        0.14966685, 0.47921691, 0.19778353, 0.15476518, 0.12425017],
       [0.00952081, 0.06664809, 0.0688639

In [ ]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [ ]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [ ]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.39489185  0.00930222]
