<a href="https://colab.research.google.com/github/SHAZAN01/Data_Analysis/blob/main/Numpy_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**numpy Library**
* numpy : stands for **Numerical Python**
* Like list in Python, array is a datastructure for numpy


* Python List is a collection of heterogenous datatypes items. It takes huge amount of time and memory for numerical computations of large data.
* Numpy array is a collection of homogenous datatypes items. It takes  very little amount of memory and time in comparision with list in terms of numerical computation of large data.

In [ ]:
# Imports all the functions that are there in numpy
# from numpy import *

# Standard Numpy Convention
import numpy as np

In [ ]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

* The number of dimensions and items in an array is  defined by its **shape**.
* The dimensions are also called as **axes**.
* ndarray : n-Dimensional array
  * 0D - Scalar
  * 1D Array - Vector
  * 2D Array - Matrix
  * 3D or more (Multi Dimension) - Tensor


In [ ]:
a = 1 #0D
b = np.array([1,2]) #1D
c = np.array([[1,2],[3,4]]) #2D
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3D
type(d)

numpy.ndarray

In [ ]:
np.array([1,2.0,'3',4])

array(['1', '2.0', '3', '4'], dtype='<U32')

In [ ]:
# np.arange(3,10)
# np.arange(3,10,2)
np.arange(17,7,-2)

array([17, 15, 13, 11,  9])

In [ ]:
# np.ones(1)
# np.ones((item,no.of items))
# np.ones((1,2))
# np.ones((1,4))
# np.ones((1,2,3))
a = np.ones((2,3,3))
# a.ndim
a
# np.ones((1,2,3,4))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a = np.ones((1,2,3,4))
a.ndim

4

In [ ]:
a = [1,2]
b = [3,4]
c = np.array([a,b])
c
# type(c)
c.size

4

In [ ]:
alist1,alist2,alist3 = [1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]
arr2 = np.array([alist1,alist2,alist3])
print(arr2)

# Size method gives you the total number of elements in the array
arr2.size

# shape method gives you the rows, columns of the array
arr2.shape

 # number of axes/dimensions
arr2.ndim

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


2

In [ ]:
alist1,alist2,alist3 = [1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]
arr2 = np.array([alist1,alist2,alist3])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
2
(3, 5)
15


In [ ]:
# 1x15
# 3x5
# 5x3
# 15x1
# arr2.shape = (15,1)
arr2.reshape(5,3)
# arr2

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

In [ ]:
# To convert any dimensions to single dimension
# arr2.flatten()
a = np.ones((1,2,3))
a.flatten()

array([1., 1., 1., 1., 1., 1.])

In [ ]:
# Slicing
arr = np.array([1,2,3,4,5])
# arr[3]
# arr[2:4]
arr[:5:2]

array([1, 3, 5])

In [ ]:
arr3 = np.array([[1, 2, 3, 4, 5],
       [6,7,8,9,10],
       [11, 12, 13, 14, 15]])
arr3
# arr[row_start:row_end, col_start:col_end]
# arr3[0:2,0:5]
arr3[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [ ]:
np.zeros((3,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
# np.full(number of items, value)
# np.full(1,2)
np.full(5,4)
np.full(10,3)

# np.full((row,col),val)
# np.full((10,2),3)
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [ ]:
# generates points within that range with equal spacing
# np.linspace(start,end,equally_spacing_value)
# np.linspace(1,5,3)
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# np.empty((1,2))
np.empty((2, 3, 2))
# It is unsafe to expect that np.empty will yield an array of all zeros.
# It may return uninitialized "garbage" values in some instances.

array([[[2.64088443e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

**Data types**

A NumPy array's type is numpy. ndarray; this is just the kind of Python object it is (similar to how type("hello") is str). dtype simply specifies how bytes in memory will be translated by a scalar (i.e. a single number) or an array, as well as how the bytes will be processed (e.g. int / float).

In [ ]:
arr = np.array([1,2])
type(arr)
arr.dtype

dtype('int64')

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
a = np.arange(10)
# np.append(a,10)
np.delete(a,6)

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [ ]:
a = np.array([7,4,9,6,8,2])
np.sort(a)

array([2, 4, 6, 7, 8, 9])

In [ ]:
a = np.array([7,4,9,6,8,2])
np.sqrt(a)

array([2.64575131, 2.        , 3.        , 2.44948974, 2.82842712,
       1.41421356])

In [ ]:
a = np.array([7,4,9,6,8,2])
np.exp(a)

array([1.09663316e+03, 5.45981500e+01, 8.10308393e+03, 4.03428793e+02,
       2.98095799e+03, 7.38905610e+00])

In [ ]:
np.random.rand(10)
np.random.randint(1,10,8)

array([1, 4, 3, 8, 3, 6, 1, 6])

In [ ]:
np.random.randn(5)

array([ 1.6466842 ,  1.22007162, -1.94865896,  1.99757274, -0.52104102])

Arithmetic with arrays

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# a+b
# a-b
# a*b
# a/b
# a//b
# a**b

array([  1,  32, 729])

In [ ]:
# Scalar arithmetic
a = np.array([1,2,3])
# a+5
a*10

array([10, 20, 30])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,0,6])
# a>b
# a<b
# a==b
a<=b

array([ True, False,  True])

Functions like mean and sum take an optional axis argument that computes the statistic over the given axis

In [ ]:
# compute mean across the columns
# a = np.array([1,2,3])
a = np.array([[1,2,3],[3,4,5]])
# a.mean(axis=0)
a.mean(axis=1)

array([2., 4.])

In [ ]:
a.sum(axis=0)
a.sum(axis=1)

array([ 6, 12])

In [ ]:
# a.cumsum(axis=1)
a.cumsum(axis=0)

In [ ]:
# a.cumprod(axis=0)
a.cumprod(axis=1)

In [ ]:
a.min()
a.max()

In [ ]:
a.var()
a.std()

In [ ]:
np.median(a)

Intersection

In [ ]:
ar1 = np.array([1,2,3,4,50])
ar2 = np.array([10,20,30,40,50])
np.intersect1d(ar1,ar2)

array([50])

In [ ]:
ar1 = np.array([[1,2,3,40,50]])
ar2 = np.array([[10,20,30,40,50]])
np.intersect1d(ar1,ar2)

array([40, 50])

Set difference

In [ ]:
ar1 = np.array([[1,2,3,4,50]])
ar2 = np.array([[10,20,30,40,50]])
np.setdiff1d(ar2,ar1)

array([10, 20, 30, 40])

Multiplication of arrays

In [ ]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([10,20,30,40,50])
ar1*ar2

array([ 10,  40,  90, 160, 250])

In [ ]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[1,2],[3,4]])
ar1*ar2

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[1,2],[3,4]])
ar1@ar2

array([[ 7, 10],
       [15, 22]])

In [ ]:
a = list(range(10))
b = list(range(10))
c =[]
def add_lists():
    for i in range(len(a)):
        c.append(a[i]+b[i])
    return c
add_lists()

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
import numpy as np
a = np.arange(10)
b = np.arange(10)
def add_arrays():
    return a+b
add_arrays()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
from timeit import Timer
t1 = Timer('add_lists()','from __main__ import add_lists')
print(t1.timeit(100000))

0.30294305799998256


In [ ]:
t2 = Timer('add_arrays()','from __main__ import add_arrays')
print(t2.timeit(100000))

0.0743289619999814


Stacking

1. hstack() - rows must be same
2. vstack() - columns must be same
3. column_stack()  - rows & columns must be same


In [ ]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([10,20,30,40,50])
np.hstack((ar1,ar2))

array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])

In [ ]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([10,20,30,40,50])
np.vstack((ar1,ar2))

In [ ]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([10,20,30,40,50])
np.column_stack((ar1,ar2))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
b = np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
c = np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])

np.column_stack((a,b,c))

array([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
       [11, 12, 13, 14, 11, 12, 13, 14, 11, 12, 13, 14]])

In [ ]:
# concatenate
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])

np.concatenate((a,b),axis=0) #vstack
# np.concatenate((a,b),axis=1) #hstack

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ar1 = np.array([[1,2,3,4,5]])
# ar1.T
ar1.transpose()

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# 2x6 matrix
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

save and load an array

In [ ]:
a = np.array([[1,2],[3,4]])
np.save('array_A',a)

In [ ]:
np.load('array_A.npy')

array([[1, 2],
       [3, 4]])

Example

In [ ]:
friends = np.array(['Tom', 'Joy', 'Bill', 'Tom', 'Gem', 'Ash', 'Sam'])
# scores = np.random.randn(7,4)
scores = np.random.randint(1,101,(7,4))
print(scores)

[[68 88 20 31]
 [62 99 80 54]
 [54 32 78 62]
 [56 20 88 25]
 [87 40 78 61]
 [26 54 67 80]
 [97 63 99 89]]


In [ ]:
# Scores of Tom?
friends == 'Tom'

array([ True, False, False,  True, False, False, False])

In [ ]:
scores[friends == 'Tom']

array([[27, 72, 81, 56],
       [30, 18, 33, 39]])

In [ ]:
# scores[friends == 'Tom'][:,:2]
scores[friends == 'Tom',:2]

array([[27, 72],
       [30, 18]])

In [ ]:
# other then Tom
# scores[friends != 'Tom']
scores[~(friends == 'Tom')]

array([[ 5, 16,  1, 45],
       [27, 47, 41, 35],
       [26, 50, 61, 29],
       [87, 91,  5, 78],
       [40, 65, 72, 71]])

In [ ]:
# Tom, Sam
scores[(friends=='Tom') | (friends=='Sam')]

array([[27, 72, 81, 56],
       [30, 18, 33, 39],
       [40, 65, 72, 71]])

In [ ]:
# more than 50
scores[scores>50]
# how many scores are more than 50
# scores[scores>50].size
len(scores[scores>50])

10

In [ ]:
# make it 0 for scores less than 50
scores[scores<50] = 0
scores

array([[ 0, 72, 81, 56],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0, 50, 61,  0],
       [87, 91,  0, 78],
       [ 0, 65, 72, 71]])

In [ ]:
# scores which is not a zero
scores[scores != 0]

array([72, 81, 56, 50, 61, 87, 91, 78, 65, 72, 71])

In [ ]:
# scores
# Double the Tom and Bill scores and reduce other scores to half of it.
scores[(friends == 'Tom') | (friends == 'Bill') ] *= 2
scores[(friends != 'Tom') | (friends != 'Bill') ] //= 2
scores

array([[136, 176,  40,  62],
       [ 31,  49,  40,  27],
       [108,  64, 156, 124],
       [112,  40, 176,  50],
       [ 43,  20,  39,  30],
       [ 13,  27,  33,  40],
       [ 48,  31,  49,  44]])

In [ ]:
# np.where(scores[scores != 0])
scores

array([[136, 176,  40,  62],
       [ 31,  49,  40,  27],
       [108,  64, 156, 124],
       [112,  40, 176,  50],
       [ 43,  20,  39,  30],
       [ 13,  27,  33,  40],
       [ 48,  31,  49,  44]])

In [ ]:
a = np.arange(10)
# a[a%2 == 0]
np.where(a%2 == 0)
# convert all odd to value 10
np.where(a%2 == 0, a,10) # condition for false, input, value
np.where(((a%2)!=0),10,a) # condition for true, value, input

array([ 0, 10,  2, 10,  4, 10,  6, 10,  8, 10])

In [ ]:
b = 10
np.where(a%2 == 0, b,a)

In [ ]:
#repeat
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.repeat((a,b),3).reshape(6,3)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [ ]:
np.tile(a,3).reshape(3,3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
a = np.arange(9).reshape(3,3)
a = a[:,[1,0,2]]
a

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)
a[[1,0,2],[2,1,0]]
a[1,1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)
# a[:,::-1]
# a[::-1,:]
a[::-1,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [ ]:
c = np.array([1,2,3,4,5,7])
d = np.array([8,7,3,4,1,0])
# np.vectorize(function)(array1,array2)
def greater(c,d):
    if c>d:
        return c
    else:
        return d

np.vectorize(greater)(c,d)


array([8, 7, 3, 4, 5, 7])

In [ ]:
c = np.array([1,12,3,14,5,17])
d = np.array([8,7,3,4,1,0])
e = np.array([18,7,13,4,11,10])
def greater1(num1,num2,num3):
    if (num1 >= num2) and (num1 >= num3):
        largest = num1
    elif (num2 >= num1) and (num2 >= num3):
        largest = num2
    else:
        largest = num3
    return largest
np.vectorize(greater1)(c,d,e)

array([18, 12, 13, 14, 11, 17])